# Baysis Port to Design Port Map
set_property PACKAGE_PIN $CLOCK_PIN [get_ports CLOCK]
set_property PACKAGE_PIN $PMOD_JXADC10 [get_ports PHI2]

set_property PACKAGE_PIN $LED0 [get_ports {LED_OUT[0]}]
set_property PACKAGE_PIN $LED1 [get_ports {LED_OUT[1]}]
set_property PACKAGE_PIN $LED2 [get_ports {LED_OUT[2]}]
set_property PACKAGE_PIN $LED3 [get_ports {LED_OUT[3]}]
set_property PACKAGE_PIN $LED4 [get_ports {LED_OUT[4]}]
set_property PACKAGE_PIN $LED5 [get_ports {LED_OUT[5]}]
set_property PACKAGE_PIN $LED6 [get_ports {LED_OUT[6]}]
set_property PACKAGE_PIN $LED7 [get_ports {LED_OUT[7]}]

set_property PACKAGE_PIN $PMOD_JB1 [get_ports {ADDRESS_IN[0]}]
set_property PACKAGE_PIN $PMOD_JB7 [get_ports {ADDRESS_IN[1]}]
set_property PACKAGE_PIN $PMOD_JB2 [get_ports {ADDRESS_IN[2]}]
set_property PACKAGE_PIN $PMOD_JB8 [get_ports {ADDRESS_IN[3]}]
set_property PACKAGE_PIN $PMOD_JB3 [get_ports {ADDRESS_IN[4]}]
set_property PACKAGE_PIN $PMOD_JB9 [get_ports {ADDRESS_IN[5]}]
set_property PACKAGE_PIN $PMOD_JB4 [get_ports {ADDRESS_IN[6]}]
set_property PACKAGE_PIN $PMOD_JB10 [get_ports {ADDRESS_IN[7]}]
set_property PACKAGE_PIN $PMOD_JC1 [get_ports {ADDRESS_IN[8]}]
set_property PACKAGE_PIN $PMOD_JC7 [get_ports {ADDRESS_IN[9]}]
set_property PACKAGE_PIN $PMOD_JC2 [get_ports {ADDRESS_IN[10]}]
set_property PACKAGE_PIN $PMOD_JC8 [get_ports {ADDRESS_IN[11]}]
set_property PACKAGE_PIN $PMOD_JC3 [get_ports {ADDRESS_IN[12]}]
set_property PACKAGE_PIN $PMOD_JC9 [get_ports {ADDRESS_IN[13]}]
set_property PACKAGE_PIN $PMOD_JC4 [get_ports {ADDRESS_IN[14]}]
set_property PACKAGE_PIN $PMOD_JC10 [get_ports {ADDRESS_IN[15]}]

set_property PACKAGE_PIN $PMOD_JA10 [get_ports {DATA[0]}]
set_property PACKAGE_PIN $PMOD_JA4 [get_ports {DATA[1]}]
set_property PACKAGE_PIN $PMOD_JA9 [get_ports {DATA[2]}]
set_property PACKAGE_PIN $PMOD_JA3 [get_ports {DATA[3]}]
set_property PACKAGE_PIN $PMOD_JA8 [get_ports {DATA[4]}]
set_property PACKAGE_PIN $PMOD_JA2 [get_ports {DATA[5]}]
set_property PACKAGE_PIN $PMOD_JA7 [get_ports {DATA[6]}]
set_property PACKAGE_PIN $PMOD_JA1 [get_ports {DATA[7]}]

set_property PACKAGE_PIN $PMOD_JXADC4 [get_ports RESB]
set_property PACKAGE_PIN $PMOD_JXADC9 [get_ports SYNC]
set_property PACKAGE_PIN $PMOD_JXADC3 [get_ports RWB]
set_property PACKAGE_PIN $PMOD_JXADC8 [get_ports RDY]
set_property PACKAGE_PIN $PMOD_JXADC2 [get_ports IRQB]
set_property PACKAGE_PIN $PMOD_JXADC1 [get_ports PIO_I2C_DATA_STREAMER_SCL]
set_property PACKAGE_PIN $PMOD_JXADC7 [get_ports PIO_I2C_DATA_STREAMER_SDA]
set_property PACKAGE_PIN $BTN_C [get_ports Reset]
set_property PACKAGE_PIN $SW15 [get_ports SingleStep]

set_property PACKAGE_PIN $SEVSEG_CATHODE_A [get_ports {PIO_7SEG_SEGMENTS[0]}]
set_property PACKAGE_PIN $SEVSEG_CATHODE_B [get_ports {PIO_7SEG_SEGMENTS[1]}]
set_property PACKAGE_PIN $SEVSEG_CATHODE_C [get_ports {PIO_7SEG_SEGMENTS[2]}]
set_property PACKAGE_PIN $SEVSEG_CATHODE_D [get_ports {PIO_7SEG_SEGMENTS[3]}]
set_property PACKAGE_PIN $SEVSEG_CATHODE_E [get_ports {PIO_7SEG_SEGMENTS[4]}]
set_property PACKAGE_PIN $SEVSEG_CATHODE_F [get_ports {PIO_7SEG_SEGMENTS[5]}]
set_property PACKAGE_PIN $SEVSEG_CATHODE_G [get_ports {PIO_7SEG_SEGMENTS[6]}]
set_property PACKAGE_PIN $SEVSEG_CATHODE_DOT [get_ports {PIO_7SEG_SEGMENTS[7]}]
set_property PACKAGE_PIN $SEVSEG_ANODE0 [get_ports {PIO_7SEG_COMMON[0]}]
set_property PACKAGE_PIN $SEVSEG_ANODE1 [get_ports {PIO_7SEG_COMMON[1]}]
set_property PACKAGE_PIN $SEVSEG_ANODE2 [get_ports {PIO_7SEG_COMMON[2]}]
set_property PACKAGE_PIN $SEVSEG_ANODE3 [get_ports {PIO_7SEG_COMMON[3]}]

# Buttons
set_property PACKAGE_PIN $BTN_L [get_ports {I_SWITCHES[0]}]
set_property PACKAGE_PIN $BTN_R [get_ports {I_SWITCHES[1]}]
set_property PACKAGE_PIN $BTN_U [get_ports {I_SWITCHES[2]}]
set_property PACKAGE_PIN $BTN_D [get_ports {I_SWITCHES[3]}]

# Slide switches
set_property PACKAGE_PIN $SW0 [get_ports {I_SWITCHES[4]}]
set_property PACKAGE_PIN $SW1 [get_ports {I_SWITCHES[5]}]
set_property PACKAGE_PIN $SW2 [get_ports {I_SWITCHES[6]}]
set_property PACKAGE_PIN $SW3 [get_ports {I_SWITCHES[7]}]
set_property PACKAGE_PIN $SW4 [get_ports {I_SWITCHES[8]}]
set_property PACKAGE_PIN $SW5 [get_ports {I_SWITCHES[9]}]
set_property PACKAGE_PIN $SW6 [get_ports {I_SWITCHES[10]}]
set_property PACKAGE_PIN $SW7 [get_ports {I_SWITCHES[11]}]
set_property PACKAGE_PIN $SW8 [get_ports {I_SWITCHES[12]}]
set_property PACKAGE_PIN $SW9 [get_ports {I_SWITCHES[13]}]
set_property PACKAGE_PIN $SW10 [get_ports {I_SWITCHES[14]}]
set_property PACKAGE_PIN $SW11 [get_ports {I_SWITCHES[15]}]