# All ports 3.3volt
# FPGA 100mhz clock
set_property IOSTANDARD LVCMOS33 [get_ports CLOCK]
set_property IOSTANDARD LVCMOS33 [get_ports {ADDRESS_IN[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports PHI2]
set_property IOSTANDARD LVCMOS33 [get_ports RESB]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC]
set_property IOSTANDARD LVCMOS33 [get_ports RWB]
set_property IOSTANDARD LVCMOS33 [get_ports RDY]
set_property IOSTANDARD LVCMOS33 [get_ports IRQB]
set_property IOSTANDARD LVCMOS33 [get_ports PIO_I2C_DATA_STREAMER_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports PIO_I2C_DATA_STREAMER_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports Reset]
set_property IOSTANDARD LVCMOS33 [get_ports SingleStep]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_OUT[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {I_SWITCHES[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PIO_7SEG_COMMON[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PIO_7SEG_SEGMENTS[*]}]

set_property PULLTYPE PULLUP [get_ports PIO_I2C_DATA_STREAMER_SDA]
set_property PULLTYPE PULLDOWN [get_ports {I_SWITCHES[*]}]
set_property PULLTYPE PULLDOWN [get_ports {DATA[*]}]
set_property PULLTYPE PULLDONW [get_ports {ADDRESS_IN[*]}]
